apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-sample-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: mcas
  sources:
    - repoURL: {{ .Values.deploy.chartRepoUrl }}
      chart: sample-app
      targetRevision: {{ .Values.deploy.chartRevision }}
      helm:
        valuesObject:
          mongodb:
            connectionStringSecret: "mongodb-admin-my-user"
  destination:
    name: ""
    namespace: {{ .Values.deploy.namespace }}
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
